### ISSUE TITLE
line at bottom of the table for FT_PLAIN_STYLE

### ISSUE THREAD

**Issue by pkbehera** [seleznevae/libfort#11]
```
#include <iostream>
#include "../src/fort.hpp"

int main(int argc, char** argv) {
  fort::table table;
  table.set_border_style(FT_PLAIN_STYLE);
  table << fort::header << "A"
        << "B" << fort::endr;

  int n_rows = argc > 1 ? std::stoi(argv[1]) : 5;
  for (int i = 0; i < n_rows; i++) {
    table << 3.14 << 12345 << fort::endr;
  }
  std::cout << table.to_string() << std::endl;
  return 0;
}
```
Can you build and run this code (accepts number of rows to be rendered as an argument):

```
~/libfort$ ./a.out 3
 -------------- 
  A      B      
 -------------- 
  3.14   12345  
  3.14   12345  
  3.14   12345  
                

~/libfort$ ./a.out 2
 -------------- 
  A      B      
 -------------- 
  3.14   12345  
  3.14   12345  
                

~/libfort$ ./a.out 1
 -------------- 
  A      B      
 -------------- 
  3.14   12345  
 -------------- 
```
Note the dashed line at the bottom of the table when **there is only one row** (other than the header). This line **vanishes** if I have more than one row in the table (other than the header). Isn't this a bug?

**Comment by seleznevae** [comment]
Hi, thanks for reporting. 
That shouldn't be there seems like a bug.

**Comment by seleznevae** [comment]
Merged fix to `develop` branch. Also modified `FT_PLAIN_STYLE` and `FT_SIMPLE_STYLE` - removed redundant blank lines at the bottom of the table and also removed redundant space on the left and right margin. For your example it should be like :
```
$ ./a.out 0
-------
 A   B 
-------

$ ./a.out 1
--------------
 A      B     
--------------
 3.14   12345 

$ ./a.out 2
--------------
 A      B     
--------------
 3.14   12345 
 3.14   12345 

$ ./a.out 3
--------------
 A      B     
--------------
 3.14   12345 
 3.14   12345 
 3.14   12345 

```

**Comment by pkbehera** [comment]
I kinda liked that line at the end of the table (in my use case I show multiple tables one after another on the console, so the line would be a nice demarcation between 2 tables)

**Comment by seleznevae** [comment]
I think for such styles as `FT_PLAIN_STYLE` and `FT_SIMPLE_STYLE` it is better to not have this default blank lines on the borders of the tables because it is easily to imagine a person who won't need them for his application. 

However, please note that there is an explicit mechanism to add this blank spaces for the table: `ft_set_tbl_prop(table, FT_TPROP_BOTTOM_MARGIN, 1)` for bottom lines. If you don't want to invoke it for each table you can use call `ft_set_default_tbl_prop(FT_TPROP_BOTTOM_MARGIN, 1)` once. From my point of view it seems better to do it explicitly.
