### ISSUE TITLE
Are there utility APIs to know if a table is empty, number of rows/columns in it etc?

### ISSUE THREAD

**Issue by pkbehera** [seleznevae/libfort#26]
I don't see any APIs like this. I can know if the table is empty by checking if `to_string` returns empty, but an API will help!

**Comment by seleznevae** [comment]
Hi! Added functions `ft_is_empty` to C API and `is_empty` to C++ API and merged to `develop` branch.

**Comment by pkbehera** [comment]
thanks for `is_empty()`, do apis like `row_count()` `column_count()` make sense?

**Comment by seleznevae** [comment]
Hard to say. I wouldn't hurry adding them. Don't want to add functions to API if it is not clear how they would be used. At first it seems easy. But maybe there can be some problems since it is possible to expand cells for several columns. 
So I think it is better to leave it as is. Let's take a break and keep the issue open for some time. If somebody else wants this functions  he'll write his thoughts about their necessity of these functions and we'll add them.

**Comment by pkbehera** [comment]
I agree that columns can be be broken/merged, but I don't think same thing can be done with rows, so a `row_count()` API should not be problematic. In fact I saw that you are checking `row_count() == 0` in `is_empty()`

**Comment by seleznevae** [comment]
Added function to get number of rows in the table. Resolving the issue.
Feel free to reopen if needed.
