### ISSUE TITLE
Integration as package into Alpine Linux

### ISSUE THREAD

**Issue by pdietl** [seleznevae/libfort#3]
Hey there. I love the library! And so I would like to know if you would be okay with me packaging it as a dev package for Alpine Linux. 

To do this, I probably need to package fort.h, fort.hpp, and fort.a into a dev package.
If you are interested in adding support for generating a .so file, then I could potentially also make a regular library package just containing that. 

Finally, it would be helpful if you could make a release so that I can make a URL directly to your repo to grab the source tarball for packaging and pointing others to your great library.

Thought on this?

**Comment by seleznevae** [comment]
Hello and thanks for kind words.
No objections. I would be glad and grateful if you do a package and make it more usable in the distribution that you use.
About release. I also thought about that. At the moment I am doing internal refactoring since internal implementation is rather messy and I have plans to add normal UTF-8 support and without refactoring it will be hard to do. My initial plans were to make a release after that work. But to be honest I have no idea how much time it will take to finish it (maybe a month or two). So maybe it is not a bad idea to make release now (something like version 0.1.0). And then after several months I'll just make another release. 

If it is not urgent, please, give me a few days, I'll try to revise API, doc strings and arrange release here on github. 

Also some thoughts about files to add to the github release. There should be `fort.c` and `fort.h`. And at this point I am not sure about `fort.hpp`. For me at the moment it is a little bit experimental and I need to think a little bit about it. By the way, did you use C API (fort.h) of C++ wrappers from (fort.hpp)?

**Comment by pdietl** [comment]
Good to hear from you. Yes I can wait for any refactoring you'd like to make before the initial release. I think it's a good idea to just make a 0.1.0 for now and then in a few months make another release. 

As for files to add to the release, I'm pretty sure that Github releases simply contain all the files of the repo, so there should not be any need to choose specific files.

On the subject of static/dynamic libraries, Alpine Linux does not really use source packages, and so including a `.c' file in the final binary package would not be allowed. The process I will follow is to create a package file which describes how to build the package and then describe which build artifacts to include in the binary package. So I will include the `.h' and `.hpp' source files directly for the 'dev' package, but for the library package, I would need to include a `.so' file, unless we only add a `.a' version of the library to the dev package. All of this to say that I'd like cmake to output a shared library for your library.

The project that I'm trying to package on Alpine that has a dependency on your library is written in C, so I'm using the `.h' file.

**Comment by seleznevae** [comment]
Ok. Then I'll try to revise code a little bit and my CMakeFiles to produce shared library.
Feel free to write any problems that you encounter in this thread.

**Comment by seleznevae** [comment]
Hello, I've made a release.
Here is a short instruction how you can build.
```
curl https://codeload.github.com/seleznevae/libfort/tar.gz/v0.1.0 -o libfort.tar.gz
tar -xvf libfort.tar.gz
cd libfort-0.1.0/

mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
# the command below will build library and tests
make
# at this point libfort.so in the build directory
ctest -VV   # if need to run tests on target platform

#if you don't need tests and need only to build library, please replace 'make' with 'make fort'
```
If something is done wrong or is inconvenient, please write I'll try to fix.

**Comment by pdietl** [comment]
Woo. I will try to make the PR tonight for this package.

**Comment by pdietl** [comment]
Could you add an install target that respects "DESTDIR" and installs the two header files into /usr/include and installs the library into /usr/lib?

**Comment by pdietl** [comment]
I could also use a chain of `.so` files, like `libfort.so.0.1.0` and `libfort.so.0 -> libfort.so.0.1.0`
.

**Comment by seleznevae** [comment]
Hello, I've made some changes in the branch `issue-3`. This is how you can check current version:
```bash
git clone https://github.com/seleznevae/libfort
cd libfort
git checkout issue-3

mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON  -DCMAKE_INSTALL_PREFIX=/usr
# the command below will build library and tests
make
ctest -VV   # if need to run tests on target platform
# if you don't need tests and need only to build the library, please replace 'make' with 'make fort'

make install # or maybe 'sudo make install' 

```

Please pay attention to `DCMAKE_INSTALL_PREFIX`. It specifies install path prefix. If you set it to `/usr`  then library will be install to `/usr/include` and `/usr/lib`. 
If everything is fine I'll create another release and you will able to download via direct link.

**Comment by pdietl** [comment]
Yes this looks great!

**Comment by seleznevae** [comment]
I've made release v.0.1.1. You can download it directly:
```bash
curl https://codeload.github.com/seleznevae/libfort/tar.gz/v0.1.1 -o libfort.tar.gz
```

**Comment by pdietl** [comment]
Here's the PR waiting for testing/approval https://github.com/alpinelinux/aports/pull/8027

**Comment by seleznevae** [comment]
I see there are problems with builds on other platforms. 
Build failed because of '-Werror'. I think it shouldn't be in my cmake files.

**Comment by seleznevae** [comment]
Released version 0.1.2 with removed from the build process '-Werror' flag. Hope it will help.

**Comment by pdietl** [comment]
I made a PR that I think will solve the problem without removing Werror

**Comment by seleznevae** [comment]
Sorry, I've just noticed. I'll see it.

**Comment by pdietl** [comment]
Could you draft another release? Then I will modify my package PR to use the new version.
In my opinion it's good that you have so many warning flags turned on. Perhaps you'd consider putting the `-Werror` flag back on? :)

**Comment by seleznevae** [comment]
This flag `-Werror` is a little bit controversial. There are some pros and cons. One may argue that it should be explicitly set by the user in CI or in package description ... 
I can revert it back so that we can check that compilation is done without warnings. But I must say that if at some point I or somebody else will encounter case when compiler will generate some dummy warnings at some specific platform it may be easily removed again. Please keep that in mind. So you shouldn't assume that it by default always there. 
If you are okay with that fact I will return it.

**Comment by pdietl** [comment]
You make a good point. Let's leave the flag out and I will add it back in explicitly as part of the package build. Does that sound like a good solution?

**Comment by seleznevae** [comment]
That sounds good to me. I'll draft release without this flag.

**Comment by seleznevae** [comment]
Released version v0.1.3

**Comment by seleznevae** [comment]
Hello, I noticed in https://github.com/alpinelinux/aports/pull/8027/files that you have `binutils-gold`. I then noticed that for all gcc builds I have option `-fuse-gold`. Is that the reason why you have to add it or something else?
Anyway, as far as I remember I think that I added it because there were some bugs with sanitizers with some gcc versions. Therefore in `develop` I made some changes - now I add `-fuse-gold` only for special builds (sanitizers ...).  
Not sure this is important. But in case guys from alpine linux will say something about `binutils-gold` maybe it can be avoided for ordinary builds.

**Comment by pdietl** [comment]
Yeah I was having trouble building without those added

**Comment by pdietl** [comment]
Yeah I don't think they like adding gold. Can you release your 0.1.4?

**Comment by seleznevae** [comment]
Done. Please check version 0.1.4.

**Comment by pdietl** [comment]
Alright it's all merged in! Thanks for you help. 

Now for me to make a PR for my project which is using your library haha.

**Comment by pdietl** [comment]
What do you think about adding the production of a pkg-config file? The project I want to use this library with uses Meson to build it, and thus uses `.pc` files to find dependencies.

**Comment by seleznevae** [comment]
I am okay with that. 
I pushed some changes for that in branch `add_package_config_files` and create PR - https://github.com/seleznevae/libfort/pull/6. Please check if it suits you and everything is fine/

**Comment by pdietl** [comment]
Looks good to me.

**Comment by seleznevae** [comment]
Please try version 0.1.5.

**Comment by pdietl** [comment]
All good
