### ISSUE TITLE
Undefined reference while building shared library that uses libfort

### ISSUE THREAD

**Issue by neel** [seleznevae/libfort#45]
Everything works file is the library is static. But when `SHARED` is added to `add_library` then it gives linker error.

```
project(fortapp)

add_subdirectory(libfort)
add_library(fortapplib SHARED lib.cpp)
target_link_libraries(fortapplib fort)

add_executable(fortapp main.cpp)
target_link_libraries(fortapp fortapplib)
```

With the above CMake configuration I get 

```
[1/3] Building CXX object CMakeFiles/fortapplib.dir/lib.cpp.o
[2/3] Linking CXX shared library libfortapplib.so
FAILED: libfortapplib.so 
: && /usr/bin/c++ -fPIC    -shared -Wl,-soname,libfortapplib.so -o libfortapplib.so CMakeFiles/fortapplib.dir/lib.cpp.o  libfort/lib/libfort.a && :
/usr/bin/ld: libfort/lib/libfort.a(fort.c.o): relocation R_X86_64_PC32 against symbol `fort_calloc' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
*** Failure: Exit code 1 ***
```

**Comment by seleznevae** [comment]
Added option `POSITION_INDEPENDENT_CODE` for main library target (https://github.com/seleznevae/libfort/commit/90265dd628f3146428690855c5340ba35035d002). 
Hope it will work for you.
Resolving the issue. In case fix doesn't help, please reopen  the issue.

**Comment by neel** [comment]
Can you provide an example on how it has to be used ? And what it will do ?

**Comment by seleznevae** [comment]
As I understood the problem was that `libfort` sources were compiled without `-fPIC` compiler option.
`POSITION_INDEPENDENT_CODE` is a target property. As I understand it means that when sources are compiled they should always be compiled with appropriate flags to turn on position independent codes. So in a nutshell: you don't have to do anything, in theory libfort library sources are now always compiled with -fPIC which should allow you to build your sources (your compiler complained that libfort sources were build without this option).
